### PR TITLE
Migrate to Capacitor 5

### PR DESCRIPTION
**Pull request by Nevvulo**
Updates the plugin to support Capacitor 5.
I've confirmed this is working for Android and iOS, tested in the simulator and through `npm run verify`

- Version 1.0.3 (and lower) will target Capacitor 3
- Version 2.0.0 will target Capacitor 4
- Version 3.0.0 will target Capacitor 5

### CODE REVIEW

**Comment by Nevvulo** [comment]
I've confirmed the messenger dialog is working correctly with Capacitor 5 on both iOS and Android

**Comment by anonimitoraf** [comment]
Just confirming: do these IOS breaking code changes not affect us? https://capacitorjs.com/docs/updating/plugins/5-0#ios

**Comment by Nevvulo** [comment]
I don't believe so, they mention this:
> The vast majority of users should not experience any issues since the status quo is to use the macro to generate conformance to CAPBridgedPlugin. Any users who cast to CAPBridgedPlugin to or manually conform to CAPBridgedPlugin without the macro will be affected.

We do not cast to `CAPBridgedPlugin` explicitly anywhere, searched through all plugins, and we do use the macro for all plugins

**Comment by anonimitoraf** [comment]
Sorry just realized I don't get Slack notifications for this repo

**Review by anonimitoraf — APPROVED** [review]

**Pull request merged**
